[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-pytorch-lightning"
version = "0.1.0"
description = "Federated Learning Quickstart with Flower and PyTorch Lightning"
authors = [{ name = "The Flower Authors", email = "hello@flower.ai" }]
dependencies = [
    "flwr>=1.9.0,<2.0",
    "flwr-datasets[vision]>=0.0.2,<1.0.0",
    "pytorch-lightning==1.6.0",
    "torchvision==0.14.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
