[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vertical-fl"
version = "1.0.0"
description = "PyTorch Vertical FL with Flower"
license = { text = "Apache License (2.0)" }
dependencies = [
    "flwr[simulation]>=1.9.0,<2.0",
    "matplotlib==3.7.3",
    "numpy==1.24.4",
    "pandas==2.0.3",
    "scikit-learn==1.3.2",
    "torch==2.1.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[flower]
publisher = "$username"

[flower.components]
serverapp = "vertical_fl.serverapp:app"
clientapp = "vertical_fl.clientapp:app"

[flower.engine]
name = "simulation"

[flower.engine.simulation.supernode]
num = 3
