[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-fastai"
version = "0.1.0"
description = "Fastai Federated Learning Quickstart with Flower"
authors = [{ name = "The Flower Authors", email = "hello@flower.ai" }]
dependencies = [
    "flwr>=1.9.0,<2.0",
    "fastai==2.7.14",
    "torch==2.2.0",
    "torchvision==0.17.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
